name: minio-dotnet GitHub actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.810
    - name: Install dependencies
      run: dotnet restore -v Minimal
    - name: Build
      run: dotnet build -c Release
    - name: After Build
      run:  dotnet pack ./Minio/Minio.csproj --no-build -c Release -o ./artifacts
    - name: Test
      run: dotnet test ./Minio.Tests/Minio.Tests.csproj -f netcoreapp2.1
